### ISSUE TITLE
[FEATURE REQ] Add preferred room capacity Text field to Settings page

### ISSUE THREAD

**Issue by Propo41** [Propo41/bookify#35]
The task is to add a text field in the settings page that will save the preferred room capacity in the local storage. 

The text field should utilize the existing component that is in the homepage
 ![Screenshot_20240928-105705.jpg](https://github.com/user-attachments/assets/d9f3e601-9f2f-4dd8-9f20-df176acd4d0e)

**Comment by Miloua91** [comment]
hey, I was able to add the the preferred room capacity and it works fine 

![image](https://github.com/user-attachments/assets/d16f8e24-7b8c-4fad-ac6a-d63158e290fb)

but I need more details about the code

in **helpers/cache.ts** you have these values and they are assiged as strings 

``` typescript
type CacheItems = 'access_token' | 'floor' | 'floors' | 'duration' | 'seats';
```
and I added seats here but the issue is that they are all assinged strings but seats is a number in the frontend and to solve that issue I had to added it to the form like this

``` typescript
      const seats = await cacheService.get('seats');
      if (seats) {
        setFormData((prevFormData) => ({
          ...prevFormData,
          seats: Number(seats),
        }));
      }
```

and save it to cache like this

``` typescript
    await cacheService.save('seats', formData.seats.toString());
```

Like I said it works fine but we can make the code more rigorous, what do you think?

There would be alot of changes to the **cache.ts** file I think?

**Comment by Miloua91** [comment]
Also when you logout the floor string gets removed from cache, is it intentional?

from **api.ts**

```typescript
  async logout() {
    try {
      const headers = await this.getHeaders();
      const res = await this.client.post('/logout', {
        headers,
      });

      return res.data as ApiResponse<boolean>;
    } catch (error: any) {
      console.log(error);
    } finally {
      await this.cacheService.remove('access_token');
      await this.cacheService.remove('floors');
      await this.cacheService.remove('floor');
    }
  }
  ```

**Comment by Propo41** [comment]
> hey, I was able to add the the preferred room capacity and it works fine
> 
> ![image](https://private-user-images.githubusercontent.com/80211751/372496849-d16f8e24-7b8c-4fad-ac6a-d63158e290fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTQzMzYsIm5iZiI6MTcyNzc5NDAzNiwicGF0aCI6Ii84MDIxMTc1MS8zNzI0OTY4NDktZDE2ZjhlMjQtN2I4Yy00ZmFkLWFjNmEtZDYzMTU4ZTI5MGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0NDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNGU3YTQxMDE0MmE0NzY4YWRhOTJkZDFmMTVhZGJmOGIzNzczMTYxOGJhYjRmZmQ5YzA1ZTFjNmE4Mzk5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JdHyR5Cv7bNeYSYkt5pfOtu85HFEQCX76GkF9Je1SYs)
> 
> but I need more details about the code
> 
> in **helpers/cache.ts** you have these values and they are assiged as strings
> 
> ```ts
> type CacheItems = 'access_token' | 'floor' | 'floors' | 'duration' | 'seats';
> ```
> 
> and I added seats here but the issue is that they are all assinged strings but seats is a number in the frontend and to solve that issue I had to added it to the form like this
> 
> ```ts
>       const seats = await cacheService.get('seats');
>       if (seats) {
>         setFormData((prevFormData) => ({
>           ...prevFormData,
>           seats: Number(seats),
>         }));
>       }
> ```
> 
> and save it to cache like this
> 
> ```ts
>     await cacheService.save('seats', formData.seats.toString());
> ```
> 
> Like I said it works fine but we can make the code more rigorous, what do you think?
> 
> There would be alot of changes to the **cache.ts** file I think?

Yes, the approach is correct. You can go ahead and make a PR. 
About the improvements, yeah surely there can be many. I just made the cache on the fly to make it simple. If you have any ideas, you are welcome to create an issue.

**Comment by Propo41** [comment]
> Also when you logout the floor string gets removed from cache, is it intentional?
> 
> from **api.ts**
> 
> ```ts
>   async logout() {
>     try {
>       const headers = await this.getHeaders();
>       const res = await this.client.post('/logout', {
>         headers,
>       });
> 
>       return res.data as ApiResponse<boolean>;
>     } catch (error: any) {
>       console.log(error);
>     } finally {
>       await this.cacheService.remove('access_token');
>       await this.cacheService.remove('floors');
>       await this.cacheService.remove('floor');
>     }
>   }
> ```

Yes it is intentional. This is only temporary. In the near future, the user preferences should be saved directly in the database instead of the front-end cache.
