### ISSUE TITLE
[BUG] Cannot book room after entering and removing an invalid email

### ISSUE THREAD

**Issue by Propo41** [Propo41/bookify#37]
**Describe the bug**
Cannot book a room after entering an invalid email and then removing that email

**To Reproduce**
1. Press "More options" 
2. Enter a valid email followed by an invalid email
3. Press "Book" and a validation error toast will popup
4. Remove the invalid email and press book again
5. The validation error toast will still popup

**Expected behavior**
Should allow the room to be booked after removing the invalid email

**Screenshots**
![image](https://github.com/user-attachments/assets/29113997-4f74-43ea-9e37-449559e5275e)

**Comment by HazemAbdo** [comment]
@Propo41 I'd like to work on this feature.

**Comment by Propo41** [comment]
> Hey @Propo41 any update in this issue? i would like to work on this issue.

@HazemAbdo seems to be working on it.

**Comment by HazemAbdo** [comment]
@Propo41 @imkurosaki I will start working on it next Friday as it is our weekend in Egypt.
