### ISSUE TITLE
[BUG] Horizontal scrollbar is brought up if room length is long

### ISSUE THREAD

**Issue by Propo41** [Propo41/bookify#38]
**Describe the bug**
Horizontal scrollbar comes up if the selected text length inside the dropdown is long.

**Screenshots**
![image](https://github.com/user-attachments/assets/3ae54ef5-46d4-4e29-bfa8-660be86ef494)

**Expected behavior**
There can be two possible approaches I can think of: 
1. trim the text and add "..." so that it fits the dialog
2. make the text come down on the next line instead of being on the same. But that would make the dropdown height increase which is undesirable. 

So, for now option 1 is preferred

**Comment by riteshkumarkarn** [comment]
Can you please explain the issue in more detail and tell the expected behaviour.

**Comment by Propo41** [comment]
@riteshkumarkarn updated the description.

**Comment by Miloua91** [comment]
I think this is what you are looking for?

![240930_13h08m33s_screenshot](https://github.com/user-attachments/assets/4ffdb64f-de89-4c57-8d6f-8b1164be8e8e)

**Comment by Propo41** [comment]
> I think this is what you are looking for?
> 
> ![240930_13h08m33s_screenshot](https://github.com/user-attachments/assets/4ffdb64f-de89-4c57-8d6f-8b1164be8e8e)
> 

Yes

**Comment by Miloua91** [comment]
Can you assign me this issue? thank you!
