### ISSUE TITLE
[BUG] Background UI issue in desktop.

### ISSUE THREAD

**Issue by SauravMob** [Propo41/bookify#41]

**Comment by Propo41** [comment]
@SauravMob  please describe the bug in detail and provide screenshots

**Comment by SauravMob** [comment]
![Screenshot from 2024-09-26 23-14-01](https://github.com/user-attachments/assets/098f795d-7aae-46da-bb5e-d8f83a43d96b)

See the issue in the background?

**Comment by Propo41** [comment]
Ah yes. Nice find. Would appreciate the fix
