### ISSUE TITLE
[BUG] if session is timed out, does not prompt new oAuth2.0 for login

### ISSUE THREAD

**Issue by kmsalmanrahman** [Propo41/bookify#48]
**Describe the bug**
if session is timed out, does not prompt new oAuth2.0 for login

**To Reproduce**
1. Go to URL after 24 hrs of first login
2. Click Book button
3. Shows error

**Expected behavior**
Should redirect to oAuth2.0 for re login

**Screenshots**
![image](https://github.com/user-attachments/assets/d45a5fdc-9145-4073-a114-bc2c0e5b72b6)

**Comment by Propo41** [comment]
this has been fixed now. When the user logs in to the app, it will first check if the session is valid or not. If not, they will be redirected to the login page.
