### ISSUE TITLE
[BUG] If I keep idle the app for some times, app is not refreshed; Hence schedule can be create at previous time

### ISSUE THREAD

**Issue by kmsalmanrahman** [Propo41/bookify#50]
**Bug Description** When the app is left idle for a while, it does not refresh. As a result, schedules can be created for past times.

**Steps to Reproduce**

1. Visit the app and note the current time (e.g., 2:30 PM).
2. Wait for 30 minutes until the time is now 3:00 PM.
3. Without reloading the page, click on the "Book Now" button for a 15-minute slot.
4. A schedule is created for the previous time slot (2:30–2:45 PM).

**Expected Behavior**
The app should not allow the creation of a meeting schedule for a past time. Instead, it should display an alert or toast message and refresh to update the current time.

**Screenshots**
![image](https://github.com/user-attachments/assets/3912f6b3-ab7e-4a51-84aa-a906c745eb96)

**Comment by Sauhard74** [comment]
hey  can i work on this issue

**Comment by Propo41** [comment]
@Sauhard74 please share how you will proceed with the implementation

**Comment by namansharma3007** [comment]
Can you assign this issue to me. I know how to do it. We will keep track of current time and we can add a default start like 15mins past current time. The minimum start time will keep on updating as soon as minutes changes or any other condition if we need.

**Comment by Propo41** [comment]
@namansharma3007 please go ahead

**Comment by namansharma3007** [comment]
There is some issue with the setup. The client side is not starting

**Comment by Propo41** [comment]
> There is some issue with the setup. The client side is not running
> ```
> Environment variable react-scripts start not defined
> npm ERR! Lifecycle script `env` failed with error:
> npm ERR! Error: command failed
> npm ERR!   in workspace: @bookify/client@0.1.0
> npm ERR!   at location: C:\Users\naman\Desktop\OSC\bookify\client
> ```

Please read the documentation. There shouldn't be anything wrong with the setup.

**Comment by namansharma3007** [comment]
I am getting this error:
```
2024-10-02 12:03:57 [error]: ENOENT: no such file or directory, stat 'C:\Users\naman\Desktop\OSC\bookify\client\build_web\index.html' {"service":"BookifyApp","context":"ExceptionsHandler","stack":["Error: ENOENT: no such file or directory, stat 'C:\\Users\\naman\\Desktop\\OSC\\bookify\\client\\build_web\\index.html'"]}}
```

**Comment by Propo41** [comment]
> I am getting this error:
> 
> 2024-10-02 12:03:57 [error]: ENOENT: no such file or directory, stat 'C:\Users\naman\Desktop\OSC\bookify\client\build_web\index.html' {"service":"BookifyApp","context":"ExceptionsHandler","stack":["Error: ENOENT: no such file or directory, stat 'C:\Users\naman\Desktop\OSC\bookify\client\build_web\index.html'"]}}
> 
> I am following these steps for installation:
> 
> https://github.com/Propo41/bookify/blob/develop/CONTRIBUTING.md/#installation-web

Did you try creating the `.env` files in client and server directories? The error is saying it can't find the build_web folder. Try running `npm run build` from the root directory.

**Comment by namansharma3007** [comment]
> > I am getting this error:
> > 2024-10-02 12:03:57 [error]: ENOENT: no such file or directory, stat 'C:\Users\naman\Desktop\OSC\bookify\client\build_web\index.html' {"service":"BookifyApp","context":"ExceptionsHandler","stack":["Error: ENOENT: no such file or directory, stat 'C:\Users\naman\Desktop\OSC\bookify\client\build_web\index.html'"]}}
> > I am following these steps for installation:
> > https://github.com/Propo41/bookify/blob/develop/CONTRIBUTING.md/#installation-web
> 
> Did you try creating the `.env` files in client and server directories? The error is saying it can't find the build_web folder. Try running `npm run build` from the root directory.

Yes I am. I even tried running npm run build from each individual directory. Still showing same error

**Comment by Propo41** [comment]
> > > I am getting this error:
> > > 2024-10-02 12:03:57 [error]: ENOENT: no such file or directory, stat 'C:\Users\naman\Desktop\OSC\bookify\client\build_web\index.html' {"service":"BookifyApp","context":"ExceptionsHandler","stack":["Error: ENOENT: no such file or directory, stat 'C:\Users\naman\Desktop\OSC\bookify\client\build_web\index.html'"]}}
> > > I am following these steps for installation:
> > > https://github.com/Propo41/bookify/blob/develop/CONTRIBUTING.md/#installation-web
> > 
> > 
> > Did you try creating the `.env` files in client and server directories? The error is saying it can't find the build_web folder. Try running `npm run build` from the root directory.
> 
> Yes I am. I even tried running `npm run build` from each individual directory. Still showing same error

Try this: 

1. from the root dir run: `npm run start:client` to start the react app in development mode 
2. in another terminal, run `npm run start:dev` to start the backend in development mode

This will ignore whether you have the build_web folder or not. If it still doesn't work, simply removing your node_modules folder and install it fresh

**Comment by namansharma3007** [comment]
Please check my PR I have solved the issue.
