### ISSUE TITLE
[FEATURE REQ]  After click on book button, Change room toast message should be stay at least 3 second for proper readability 

### ISSUE THREAD

**Issue by kmsalmanrahman** [Propo41/bookify#51]
**Description**
After click on book button, Change room toast message should be stay at least 3 second for proper readability 

**Steps to Reproduce**
1. Visit the URL
2. Click on book button
3. The toast message gets invisible very fast

**Expected message**
Toast message should be stay at least 3s
![image](https://github.com/user-attachments/assets/2b668016-b575-4598-a087-04e05e141138)

**Comment by Sauhard74** [comment]
hey can i work on this issue

**Comment by Propo41** [comment]
this is no longer required as we are moving to the My events page after booking a room, so the current duration is fine.

FYI @Sauhard74 @kmsalmanrahman
