### ISSUE TITLE
[FEATURE REQ] Need to be shown toast message when 

### ISSUE THREAD

**Issue by kmsalmanrahman** [Propo41/bookify#52]
**Description**
In settings menu, after click on save button not showing any toast message as "Saved successfully"

![image](https://github.com/user-attachments/assets/226211c3-d09a-4617-8f2a-8c0462921e19)

**Comment by Miloua91** [comment]
Relatively easy to implement

![240930_13h36m10s_screenshot](https://github.com/user-attachments/assets/71881cbc-6859-4385-859a-079ee653a020)

**Comment by Propo41** [comment]
> Relatively easy to implement
> 
> ![240930_13h36m10s_screenshot](https://github.com/user-attachments/assets/71881cbc-6859-4385-859a-079ee653a020)
> 

Do you want to make a PR?

**Comment by Miloua91** [comment]
I will make a PR tomorrow since hacktoberfest starts tomorrow, can you assign me the issue?
