### ISSUE TITLE
[BUG] If Guest number is bigger, showing internal error

### ISSUE THREAD

**Issue by kmsalmanrahman** [Propo41/bookify#53]
**Describe the bug**

**To Reproduce**
1. Visit app URL
2. Add guest 13 or more
3. Click on book button
4. Showing 500 internal error in network

**Expected behavior**
Should be shown appropriate error message if there is any highest limit of guest

**Screenshots**
![image](https://github.com/user-attachments/assets/160abe37-d8a0-4135-a709-ef265e55ecd8)

**Comment by Miloua91** [comment]
I can't seem to reproduce to error

![image](https://github.com/user-attachments/assets/ae3223d0-1946-4d41-9d0e-b41f2870288c)

**Comment by Propo41** [comment]
> I can't seem to reproduce to error
> 
> ![image](https://github.com/user-attachments/assets/ae3223d0-1946-4d41-9d0e-b41f2870288c)
> 

Perhaps the issue appears in the staging server where the original calender is utilized. 
https://seahorse-app-yh7s9.ondigitalocean.app/

But you cannot login unless you have an organization account and your email has been selectively added to the oauth list.

**Comment by Miloua91** [comment]
> > I can't seem to reproduce to error
> > 
> > ![image](https://github.com/user-attachments/assets/ae3223d0-1946-4d41-9d0e-b41f2870288c)
> > 
> 
> Perhaps the issue appears in the staging server where the original calender is utilized. 
> https://seahorse-app-yh7s9.ondigitalocean.app/
> 
> But you cannot login unless you have an organization account and your email has been selectively added to the oauth list.

Yes maybe,  unfortunately I can't work on this issue since I don't have an organization account
