### ISSUE TITLE
[FEATURE REQ] Simplified User Input: No Buttons Required

### ISSUE THREAD

**Issue by imkurosaki** [Propo41/bookify#54]
Description
The User-Driven Value Input feature enhances user interaction by allowing users to directly input their desired values into a text field, eliminating the need for traditional increment and decrement buttons. If the users want a bigger capacity so they can only input it and not using increment and decrement buttons.

![image](https://github.com/user-attachments/assets/dedd5286-ad9b-4df5-ab69-f3958b8e57bc)

**Comment by imkurosaki** [comment]
@Propo41 I’m interested in working on this feature. Would it be okay if I take it on?

**Comment by Propo41** [comment]
Thanks for your interest but at this time, we're not planning to implement this feature

> @Propo41 I’m interested in working on this feature. Would it be okay if I take it on?
