### ISSUE TITLE
[FEATURE REQ] UI Improvement: Change Duration Format to 'Hours and Minutes

### ISSUE THREAD

**Issue by imkurosaki** [Propo41/bookify#55]
Description:
The current UI displays durations in shorthand format (e.g., "75m"), which can be inconvenient for users who need to mentally convert this into hours and minutes. Changing the format to "1hr 15mins" would enhance clarity and improve user experience by providing immediate understanding of the duration.

![image](https://github.com/user-attachments/assets/b01a174f-2ee6-4db7-a6a6-97d8915a3bcd)

**Comment by imkurosaki** [comment]
@Propo41 I would like to work on this feature, could you please assign it to me?.

**Comment by Propo41** [comment]
> @Propo41 I would like to work on this feature, could you please assign it to me?.

This is a feature I have been wanting myself throughout the course of time but forgot to add. You are welcome to go ahead but note that the final request payload should be as it is now. This is only a visual change.

**Comment by imkurosaki** [comment]
Okay got it working on it, @Propo41 could you please add hacktoberfest label because it's my first time to participate on it.
