### ISSUE TITLE
[BUG] Fix Meeting Creation Order: New Meetings Appear at the End of the List

### ISSUE THREAD

**Issue by imkurosaki** [Propo41/bookify#62]
**Describe the bug**
When creating a new meeting, it is incorrectly positioned at the beginning of the list instead of being added to the end.

**To Reproduce**
1. Book a room
2. Then go to my event

**Expected behavior**
When a new meeting is created, it should be added to the end of the list instead of appearing at the beginning.

**Desktop (please complete the following information):**

**Comment by imkurosaki** [comment]
@Propo41 Hi, I would like to work on this feature, can you please assign it to me?

**Comment by Propo41** [comment]
> @Propo41 Hi, I would like to work on this feature, can you please assign it to me?

Nice finding! Although the events are sorted by the meeting start time, multiple events having the same start and end time should be sorted by their creation date. 

Please share how you would approach the problem

**Comment by imkurosaki** [comment]
I think the proper way to sort it is via their creation date. This approach ensures that when multiple meetings have the same start and end times, the order of the meetings reflects their actual creation sequence. In the future, if a user wants to update the start time of a meeting, having them sorted by creation date makes it easier to manage and avoid confusion. Also helps in organizing meetings effectively.

**Comment by imkurosaki** [comment]
Yes, i deleted my reply i think we need to sort via start time and if there's having the same start and end time i think we need to sort it via their creation date. I think this good. What do you think?

**Comment by Propo41** [comment]
> Yes you are right, i deleted my reply i think we need to sort via start time and if there's having the same start and end time i think we need to sort it via their creation date. I think this is good. What do you think?

Correct. But need to check if the api response contains any such field to track this. Perhaps the `updated` field?

**Comment by imkurosaki** [comment]
What about this https://developers.google.com/calendar/api/v3/reference/events#resource? there's a created date.

**Comment by Propo41** [comment]
> What about this https://developers.google.com/calendar/api/v3/reference/events#resource? there's a created date.

The one you sent is the response of an event after its creation. We need this api: https://developers.google.com/calendar/api/v3/reference/events/list

The `updated` field looks promising. But need to confirm if it works.

**Comment by imkurosaki** [comment]
Ah, I understand now! May I try working on this?

**Comment by Propo41** [comment]
> Ah, I understand now! May I try working on this?

Only if you can confirm that we can utilize the updated field sent as a response or something else. You can try out the api using the api playground that google provides
